//Creación del API donde se realizan las peticiones
//Seleccionar todos los profesores
###
GET http://localhost:9000/api

//Seleccionar un profesor
###
GET http://localhost:9000/api/1

//Agregar un profesor
###
POST http://localhost:9000/api
Content-Type: application/json

{
    "nombre": "Javier ",
    "apellidos": "Torres Yañez",
    "titulo": "Ingenieria en Sistemas Computacionales",
    "area": "TICS",
    "materias": "Base de datos"

}

//Actualizar un profesor
###
PUT http://localhost:9000/api/5
Content-Type: application/json

{
   "nombre": "Alejandra Suarez"
}

//Eliminar un profesor
###
DELETE http://localhost:9000/api/5